// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurniejMaxow.Models;

namespace TurniejMaxow.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190323171440_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TurniejMaxow.Models.FormResponse", b =>
                {
                    b.Property<int>("FormResponseID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .IsRequired();

                    b.Property<int?>("CurrBench");

                    b.Property<int?>("CurrDeadlift");

                    b.Property<int?>("CurrOhp");

                    b.Property<int?>("CurrSquat");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int?>("GoalBench");

                    b.Property<int?>("GoalDeadlift");

                    b.Property<int?>("GoalOhp");

                    b.Property<int?>("GoalSquat");

                    b.Property<int?>("Height")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<DateTime>("Signed");

                    b.Property<int?>("Weight")
                        .IsRequired();

                    b.HasKey("FormResponseID");

                    b.ToTable("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
